"""initial_schema

Revision ID: e888753de19e
Revises: 
Create Date: 2026-08-30 02:20:20.897500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = 'e888753de19e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competencies',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competencies_id'), 'competencies', ['id'], unique=False)
    op.create_index(op.f('ix_competencies_name'), 'competencies', ['name'], unique=True)
    op.create_table('evaluation_rubrics',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('question_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluation_rubrics_id'), 'evaluation_rubrics', ['id'], unique=False)
    op.create_index(op.f('ix_evaluation_rubrics_question_type'), 'evaluation_rubrics', ['question_type'], unique=False)
    op.create_table('organization_profiles',
    sa.Column('organization_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=255), nullable=False),
    sa.Column('experience_level', sa.String(length=50), nullable=True),
    sa.Column('technical_weight', sa.Float(), nullable=True),
    sa.Column('behavioral_weight', sa.Float(), nullable=True),
    sa.Column('case_study_weight', sa.Float(), nullable=True),
    sa.Column('leadership_weight', sa.Float(), nullable=True),
    sa.Column('communication_weight', sa.Float(), nullable=True),
    sa.Column('common_question_types', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('important_competencies', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('interview_stages', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('common_topics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reported_question_patterns', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('research_confidence', sa.Float(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_profiles_id'), 'organization_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_organization_profiles_organization_name'), 'organization_profiles', ['organization_name'], unique=False)
    op.create_index(op.f('ix_organization_profiles_role'), 'organization_profiles', ['role'], unique=False)
    op.create_table('organizations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('career_page_url', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('size', sa.String(length=50), nullable=True),
    sa.Column('values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_id'), 'organizations', ['id'], unique=False)
    op.create_index(op.f('ix_organizations_name'), 'organizations', ['name'], unique=True)
    op.create_table('question_intelligence',
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('question_type', sa.Enum('TECHNICAL', 'BEHAVIORAL', 'ANALYTICAL', 'CASE_STUDY', 'SITUATIONAL', 'PERSONAL_MOTIVATIONAL', 'HR_CULTURE', 'COMMUNICATION', 'CURVEBALL_STRESS', 'SALARY_LOGISTICS', 'LEADERSHIP_TEAMWORK', 'ETHICAL_INTEGRITY', 'REFLECTIVE_SELF_GROWTH', 'RAPID_FIRE_ICEBREAKER', 'FOLLOW_UP_PROBING', name='questiontypeenum'), nullable=False),
    sa.Column('role', sa.String(length=255), nullable=True),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('experience_level', sa.String(length=50), nullable=True),
    sa.Column('competencies', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('difficulty', sa.Integer(), nullable=True),
    sa.Column('frequency', sa.Float(), nullable=True),
    sa.Column('importance', sa.Float(), nullable=True),
    sa.Column('role_relevance', sa.Float(), nullable=True),
    sa.Column('company_relevance', sa.Float(), nullable=True),
    sa.Column('core_concept_relevance', sa.Float(), nullable=True),
    sa.Column('trend_relevance', sa.Float(), nullable=True),
    sa.Column('source_type', sa.Enum('OFFICIAL', 'PUBLICLY_REPORTED', 'PLATFORM_DATA', 'GENERAL_ROLE_KNOWLEDGE', 'AI_GENERATED', name='sourcetype'), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('source_date', sa.String(length=50), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_intelligence_company'), 'question_intelligence', ['company'], unique=False)
    op.create_index(op.f('ix_question_intelligence_id'), 'question_intelligence', ['id'], unique=False)
    op.create_index(op.f('ix_question_intelligence_question_type'), 'question_intelligence', ['question_type'], unique=False)
    op.create_index(op.f('ix_question_intelligence_role'), 'question_intelligence', ['role'], unique=False)
    op.create_table('question_observations',
    sa.Column('source_type', sa.Enum('OFFICIAL', 'PUBLICLY_REPORTED', 'PLATFORM_DATA', 'GENERAL_ROLE_KNOWLEDGE', 'AI_GENERATED', name='sourcetype'), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('source_title', sa.String(length=500), nullable=True),
    sa.Column('source_date', sa.String(length=50), nullable=True),
    sa.Column('retrieved_at', sa.String(length=50), nullable=True),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=255), nullable=True),
    sa.Column('claim', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_observations_company'), 'question_observations', ['company'], unique=False)
    op.create_index(op.f('ix_question_observations_id'), 'question_observations', ['id'], unique=False)
    op.create_table('users',
    sa.Column('firebase_uid', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('photo_url', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_firebase_uid'), 'users', ['firebase_uid'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('candidate_profiles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('experience_level', sa.String(length=50), nullable=True),
    sa.Column('target_role', sa.String(length=255), nullable=True),
    sa.Column('target_company', sa.String(length=255), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('years_of_experience', sa.Integer(), nullable=True),
    sa.Column('current_role', sa.String(length=255), nullable=True),
    sa.Column('current_company', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_profiles_id'), 'candidate_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_candidate_profiles_user_id'), 'candidate_profiles', ['user_id'], unique=True)
    op.create_table('candidate_skill_profiles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('competency', sa.String(length=255), nullable=False),
    sa.Column('current_score', sa.Float(), nullable=True),
    sa.Column('total_assessments', sa.Integer(), nullable=False),
    sa.Column('trend', sa.String(length=50), nullable=True),
    sa.Column('score_history', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_skill_profiles_id'), 'candidate_skill_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_candidate_skill_profiles_user_id'), 'candidate_skill_profiles', ['user_id'], unique=False)
    op.create_table('job_descriptions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=255), nullable=False),
    sa.Column('description_text', sa.Text(), nullable=False),
    sa.Column('experience_level', sa.String(length=50), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_descriptions_id'), 'job_descriptions', ['id'], unique=False)
    op.create_index(op.f('ix_job_descriptions_user_id'), 'job_descriptions', ['user_id'], unique=False)
    op.create_table('resumes',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.String(length=512), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('content_text', sa.Text(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resumes_id'), 'resumes', ['id'], unique=False)
    op.create_index(op.f('ix_resumes_user_id'), 'resumes', ['user_id'], unique=False)
    op.create_table('rubric_criteria',
    sa.Column('rubric_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('max_score', sa.Float(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['rubric_id'], ['evaluation_rubrics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rubric_criteria_id'), 'rubric_criteria', ['id'], unique=False)
    op.create_index(op.f('ix_rubric_criteria_rubric_id'), 'rubric_criteria', ['rubric_id'], unique=False)
    op.create_table('interviews',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('mode', sa.Enum('PRACTICE', 'SIMULATION', name='interviewmode'), nullable=False),
    sa.Column('status', sa.Enum('PLANNED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='interviewstatus'), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=255), nullable=True),
    sa.Column('experience_level', sa.String(length=50), nullable=True),
    sa.Column('job_description_id', sa.Uuid(), nullable=True),
    sa.Column('resume_id', sa.Uuid(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('selected_question_types', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('scores_by_competency', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_description_id'], ['job_descriptions.id'], ),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interviews_id'), 'interviews', ['id'], unique=False)
    op.create_index(op.f('ix_interviews_user_id'), 'interviews', ['user_id'], unique=False)
    op.create_table('job_requirements',
    sa.Column('job_description_id', sa.Uuid(), nullable=False),
    sa.Column('requirement_text', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_description_id'], ['job_descriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_requirements_id'), 'job_requirements', ['id'], unique=False)
    op.create_index(op.f('ix_job_requirements_job_description_id'), 'job_requirements', ['job_description_id'], unique=False)
    op.create_table('candidate_performance',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('interview_id', sa.Uuid(), nullable=False),
    sa.Column('competency', sa.String(length=255), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('max_score', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_performance_id'), 'candidate_performance', ['id'], unique=False)
    op.create_index(op.f('ix_candidate_performance_user_id'), 'candidate_performance', ['user_id'], unique=False)
    op.create_table('interview_plans',
    sa.Column('interview_id', sa.Uuid(), nullable=False),
    sa.Column('plan_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('interview_id')
    )
    op.create_index(op.f('ix_interview_plans_id'), 'interview_plans', ['id'], unique=False)
    op.create_table('interview_questions',
    sa.Column('interview_id', sa.Uuid(), nullable=False),
    sa.Column('parent_question_id', sa.Uuid(), nullable=True),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('question_type', sa.String(length=100), nullable=False),
    sa.Column('competencies', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('difficulty', sa.Integer(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=True),
    sa.Column('selection_reason', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_question_id'], ['interview_questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_questions_id'), 'interview_questions', ['id'], unique=False)
    op.create_index(op.f('ix_interview_questions_interview_id'), 'interview_questions', ['interview_id'], unique=False)
    op.create_table('answers',
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['interview_questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id')
    )
    op.create_index(op.f('ix_answers_id'), 'answers', ['id'], unique=False)
    op.create_table('interview_plan_items',
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('question_type', sa.String(length=100), nullable=False),
    sa.Column('competency', sa.String(length=255), nullable=True),
    sa.Column('allocated_minutes', sa.Integer(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['interview_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_plan_items_id'), 'interview_plan_items', ['id'], unique=False)
    op.create_index(op.f('ix_interview_plan_items_plan_id'), 'interview_plan_items', ['plan_id'], unique=False)
    op.create_table('evaluations',
    sa.Column('answer_id', sa.Uuid(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('max_score', sa.Float(), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=False),
    sa.Column('strengths', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('weaknesses', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('criteria_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('follow_up_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['answers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('answer_id')
    )
    op.create_index(op.f('ix_evaluations_id'), 'evaluations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evaluations_id'), table_name='evaluations')
    op.drop_table('evaluations')
    op.drop_index(op.f('ix_interview_plan_items_plan_id'), table_name='interview_plan_items')
    op.drop_index(op.f('ix_interview_plan_items_id'), table_name='interview_plan_items')
    op.drop_table('interview_plan_items')
    op.drop_index(op.f('ix_answers_id'), table_name='answers')
    op.drop_table('answers')
    op.drop_index(op.f('ix_interview_questions_interview_id'), table_name='interview_questions')
    op.drop_index(op.f('ix_interview_questions_id'), table_name='interview_questions')
    op.drop_table('interview_questions')
    op.drop_index(op.f('ix_interview_plans_id'), table_name='interview_plans')
    op.drop_table('interview_plans')
    op.drop_index(op.f('ix_candidate_performance_user_id'), table_name='candidate_performance')
    op.drop_index(op.f('ix_candidate_performance_id'), table_name='candidate_performance')
    op.drop_table('candidate_performance')
    op.drop_index(op.f('ix_job_requirements_job_description_id'), table_name='job_requirements')
    op.drop_index(op.f('ix_job_requirements_id'), table_name='job_requirements')
    op.drop_table('job_requirements')
    op.drop_index(op.f('ix_interviews_user_id'), table_name='interviews')
    op.drop_index(op.f('ix_interviews_id'), table_name='interviews')
    op.drop_table('interviews')
    op.drop_index(op.f('ix_rubric_criteria_rubric_id'), table_name='rubric_criteria')
    op.drop_index(op.f('ix_rubric_criteria_id'), table_name='rubric_criteria')
    op.drop_table('rubric_criteria')
    op.drop_index(op.f('ix_resumes_user_id'), table_name='resumes')
    op.drop_index(op.f('ix_resumes_id'), table_name='resumes')
    op.drop_table('resumes')
    op.drop_index(op.f('ix_job_descriptions_user_id'), table_name='job_descriptions')
    op.drop_index(op.f('ix_job_descriptions_id'), table_name='job_descriptions')
    op.drop_table('job_descriptions')
    op.drop_index(op.f('ix_candidate_skill_profiles_user_id'), table_name='candidate_skill_profiles')
    op.drop_index(op.f('ix_candidate_skill_profiles_id'), table_name='candidate_skill_profiles')
    op.drop_table('candidate_skill_profiles')
    op.drop_index(op.f('ix_candidate_profiles_user_id'), table_name='candidate_profiles')
    op.drop_index(op.f('ix_candidate_profiles_id'), table_name='candidate_profiles')
    op.drop_table('candidate_profiles')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_firebase_uid'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_question_observations_id'), table_name='question_observations')
    op.drop_index(op.f('ix_question_observations_company'), table_name='question_observations')
    op.drop_table('question_observations')
    op.drop_index(op.f('ix_question_intelligence_role'), table_name='question_intelligence')
    op.drop_index(op.f('ix_question_intelligence_question_type'), table_name='question_intelligence')
    op.drop_index(op.f('ix_question_intelligence_id'), table_name='question_intelligence')
    op.drop_index(op.f('ix_question_intelligence_company'), table_name='question_intelligence')
    op.drop_table('question_intelligence')
    op.drop_index(op.f('ix_organizations_name'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_id'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_organization_profiles_role'), table_name='organization_profiles')
    op.drop_index(op.f('ix_organization_profiles_organization_name'), table_name='organization_profiles')
    op.drop_index(op.f('ix_organization_profiles_id'), table_name='organization_profiles')
    op.drop_table('organization_profiles')
    op.drop_index(op.f('ix_evaluation_rubrics_question_type'), table_name='evaluation_rubrics')
    op.drop_index(op.f('ix_evaluation_rubrics_id'), table_name='evaluation_rubrics')
    op.drop_table('evaluation_rubrics')
    op.drop_index(op.f('ix_competencies_name'), table_name='competencies')
    op.drop_index(op.f('ix_competencies_id'), table_name='competencies')
    op.drop_table('competencies')
    # ### end Alembic commands ###
